DROP INDEX IF EXISTS Customer_PhoneNum;
DROP INDEX IF EXISTS Customer_lastName;
DROP INDEX IF EXISTS Needs_VIN;
DROP INDEX IF EXISTS Request_ID;
DROP INDEX IF EXISTS Employee_ID;
DROP INDEX IF EXISTS Car_VIN;

CREATE INDEX Customer_PhoneNum ON Customer(Phone_Num);
CREATE INDEX Customer_lastName ON Customer(Last_Name);
CREATE INDEX Needs_VIN ON Needs(VIN);
CREATE INDEX Request_ID ON Service(ID);
CREATE INDEX Employee_ID ON Mechanic(ID);
CREATE INDEX Car_VIN ON Car(VIN);